# **************************************************************
#                 Pontificia Universidad Javeriana
#         Autores: Gabriel Jaramillo, Samuel Beltran
#         Fecha: Agosto 2026
#         Materia: Procesamiento de Datos
#         Tema: Procesamiento de datos para toma de decisiones
#         Fichero: Makefile
#         Descripción: 
#             Makefile para automatización del proceso de compilación.
#             - Compila el motor de inferencia
#			  - Construye archivos de datos
# **************************************************************

run:
	perl lanza.pl

# Limpieza de archivos generados
clean:
	rm -f motor
	rm -f *.txt
	rm -f *.csv

.PHONY: all clean